### ISSUE TITLE
[Feature improvement] Query variables

### ISSUE THREAD

**Issue by anned20** [edmodo/proxyweb#15]
For queries that require input, it would be nice if you can dynamically set the variables instead of having to directly modify the SQL query.

In the config the structure could be something like this:

```yaml
misc:
  update_config:
    - title: "Add a new mysql server"
      info: "Add a new servers to the mysql_servers.  \\nhttps://proxysql.com/documentation/proxysql-configuration/"
      sql: "INSERT INTO mysql_servers(hostgroup_id,hostname,port) VALUES ({hostgroup_id},{hostname},{port});"
      variables:
        hostgroup_id:
          type: int
          label: Hostgroup ID
        hostname:
          type: string
          label: Hostname
          default: 127.0.0.1
        port:
          type: int
          label: Port
          default: 3306
```

In the interface this can be parsed and shown as input fields with the respective types and validation.

Having a query with variables would either require the SQL field to become readonly (as to not make it possible to have placeholder values without placeholders) or it should be parsed with the variables, shown in the SQL field and then be editable without placeholders.
